services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile 
    image: hawall_server
    container_name: hawall_server
    pull_policy: never
    ports:
      - 8000:8000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    develop:
      watch:
        - path: ./templates
          target: /app/templates 
          action: sync