services:
  frontend:
    depends_on:
      - backend
    build: 
      context: frontend/
      dockerfile: Dockerfile 
    image: aramk0/front_end
    container_name: front_end
    pull_policy: never
    ports:
      - 5000:5000
  backend:
    build: 
      context: backend/
      dockerfile: Dockerfile
    image: aramk0/back_end
    container_name: back_end
    pull_policy: never
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    
    #watches for realtime changes in these frontend files
    develop:
      watch:
        - path: app/frontend/templates
          target: app/frontend/templates
          action: sync
    ports:
      - 8000:8000
    volumes:
    # these are bind mounts for now, change to volume mounts in prod
     - ./logs:/app/logs
     - ./frontend:/app/frontend
     - ./backend:/app/backend
     - ./tests:/app/tests

   