services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile 
    image: hawall_server
    container_name: hawall_server
    pull_policy: never
    ports:
      - 8000:8000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://127.0.0.1:8000/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    develop:
      watch:
        - path: ./templates
          target: /app/templates 
          action: sync
    volumes:
      - ./logs:/app/logs 