apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hawall
  template:
    metadata:
      labels:
        app: hawall
    spec:
      initContainers:
      - name: frontend-files
        image: aramk0/front_end
        command:
        - sh
        - -c
        - |
          mkdir -p shared/templates shared/static
          cp -r /app/templates/* /shared/templates/
          cp -r /app/static/* /shared/static/
          echo "front-end files copied"
        volumeMounts:
        - name: frontend-files
          mountPath: /shared

      containers:
      - name: backend
        image: aramk0/back_end
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: OPENAI_API_KEY

        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: ANTHROPIC_API_KEY
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: frontend-files
          mountPath: /app/frontend
        livenessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8000
      volumes:
      - name: frontend-files
        emptyDir: {}
