name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Create logs directory
      run: mkdir -p logs
    
    - name: Build and start services
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        docker-compose build
        docker-compose up -d
    
    - name: Wait for services to be ready
      run: |
        echo "Waiting for backend service..."
        timeout 60 bash -c 'until curl -f http://localhost:8000 >/dev/null 2>&1; do sleep 2; done'
        echo "Backend is ready!"
        
        echo "Waiting for frontend service..."
        timeout 60 bash -c 'until curl -f http://localhost:5000 >/dev/null 2>&1; do sleep 2; done'
        echo "Frontend is ready!"
    
    - name: Set up Python for testing
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest httpx
    
    - name: Run tests
      run: |
        pytest tests/test.py -v
    
    - name: Show service logs on failure
      if: failure()
      run: |
        echo "=== Backend logs ==="
        docker-compose logs backend
        echo "=== Frontend logs ==="
        docker-compose logs frontend
    
    - name: Clean up
      if: always()
      run: |
        docker-compose down -v
        docker system prune -f