name: CI test

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Set up Docker Compose
        run: docker compose up -d --build

      - name: check running containers
        run: |
          docker ps -a
          ls
          docker logs back_end
          curl http://127.0.0.1:8000

     

      - name: Integration tests
        run: docker exec pytest
