name: CI test

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt
         

      - name: Set up Docker Compose
        run: docker compose up -d --build

      - name: check running containers
        run: |
          docker ps -a
          ls
          sudo chmod 777 logs/
          sudo chmod 777 logs/chat_logs.txt
          
      - name: Wait for backend to be ready
        run: |
          for i in {1..10}; do
            if curl -s http://127.0.0.1:8000; then
              echo "Backend is up!";
             exit 0;
            fi
            echo "Waiting for backend...";
            sleep 3;
              done
              echo "Backend failed to start";
              docker logs back_end
              exit 1
   
     

      - name: Integration tests
        run: docker exec pytest
